### PR TITLE
Enhance custom field

### PR DESCRIPTION
**Pull request by ymhuang0808**
This change is [Reviewable](https://reviewable.io/reviews/openisdm/vms/81)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/OpenISDM/VMS/pull/81" target="_blank">ReviewNinja

**Comment by ymhuang0808** [comment]
Fix #77

**Comment by ymhuang0808** [comment]
fix #79

**Comment by ymhuang0808** [comment]
The PR also contains #75

**Pull request merged**
